version: "3"
services:
  react-app-dev:
    container_name: react-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./.env
