version: "3"
services:
  react-app:
    container_name: react-app
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./.env
